from enum import Enum

class FLAVOR(Enum):
    MUSSARELA = "MUSSARELA"
    PEPPERONI = "PEPPERONI"
    CALABRESA = "CALABRESA"
    ATUM = "ATUM"
    BACON = "BACON"
    RUCULA = "RUCULA"
    FRANGO = "FRANGO"
    MARGUERITA = "MARGUERITA"
    PORTUGUESA = "PORTUGUESA"
    BRASILEIRA = "BRASILEIRA"
    QUATRO_QUEIJOS = "QUATRO_QUEIJOS"

    